name: multiversx_sdk
description: A comprehensive Dart library for MultiversX blockchain development, simplifying blockchain interactions for Flutter and Dart developers.
version: 0.5.0
repository: https://github.com/KLEAK-Development/multiversx

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  convert: ^3.1.1
  http: ^1.4.0
  meta: ^1.17.0
  multiversx_api: ^0.1.5
  multiversx_crypto: ^0.1.4
  pointycastle: ^4.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.0
